apiVersion: v1
kind: Service
metadata:
  labels:
    app: EnG-frontend
  name: ??????
spec:
  ports:
  - protocol: TCP
    port: 4200
    targetPort: 4200
  selector:
    app: EnG-frontend
  type: LoadBalancer
status:
  loadBalancer: {}
