apiVersion: v1
kind: Service
metadata:
  labels:
    app: EnG-frontend
  name: EnG-frontend-service
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4200
  selector:
    app: EnG-frontend
  type: LoadBalancer
status:
  loadBalancer: {}
