apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eng-frontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: eng-frontend
    spec:
      containers:
      - image: d3334/angular
        name: eng-frontend
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        imagePullPolicy: Always
        ports:
        - name: frontend-port
          containerPort: 4200
status: {}
